# Keep your local settings but allow Render to override them
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=hayat-foundation
spring.datasource.password=hayat12345foundation
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Automatically create tables based on your Java Entity files
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true